# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0107_auto_20210305_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercialoperator_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
