# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 06:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0108_auto_20210505_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmingfee',
            name='lines_aggregated',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
