# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0110_auto_20210618_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='activity_type',
            field=models.CharField(choices=[('land', 'Land'), ('marine', 'Marine'), ('Film', 'Film'), ('event', 'Event')], default='land', max_length=40, verbose_name='Activity Type'),
        ),
    ]
