# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0111_auto_20210618_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventstrails',
            name='activities_assessor',
            field=models.ManyToManyField(blank=True, null=True, to='commercialoperator.Activity'),
        ),
    ]
