# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0112_proposaleventstrails_activities_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventsparks',
            name='activities_assessor',
            field=models.ManyToManyField(blank=True, null=True, to='commercialoperator.Activity'),
        ),
    ]
