# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0113_proposaleventsparks_activities_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='require_due_date',
            field=models.BooleanField(default=False),
        ),
    ]
