# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-30 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0114_proposalstandardrequirement_require_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalstandardrequirement',
            name='require_due_date',
        ),
    ]
