# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0115_remove_proposalstandardrequirement_require_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='visible_to_external',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
