# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0122_auto_20210811_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='last_event_application_fee_date',
            field=models.DateField(blank=True, null=True, verbose_name='The last date a fee was charged for an Eventi Application'),
        ),
    ]
