# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-14 08:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0123_auto_20210811_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginvoice',
            name='property_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
