# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0128_auto_20230727_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_period', models.CharField(choices=[('2_months', '2 months'), ('1_year', '1 Year'), ('3_year', '3 Years'), ('5_year', '5 Years'), ('7_year', '7 Years'), ('10_year', '10 Years')], default='1_year', max_length=40, unique=True)),
                ('renewal_month', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['licence_period'],
            },
        ),
        migrations.CreateModel(
            name='NotificationMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(default=0)),
                ('licence_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_months', to='commercialoperator.LicencePeriod')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='commercialoperator.Approval')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationperiod',
            unique_together=set([('approval', 'notification_date')]),
        ),
    ]
