# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0128_auto_20230727_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('renewal_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='renewal_sent',
        ),
        migrations.AddField(
            model_name='renewalperiod',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='commercialoperator.Approval'),
        ),
        migrations.AlterUniqueTogether(
            name='renewalperiod',
            unique_together=set([('approval', 'renewal_date')]),
        ),
    ]
