# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0129_auto_20230905_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='reserved_licence',
            field=models.BooleanField(default=False),
        ),
    ]
