# Generated by Django 5.0.8 on 2024-11-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commercialoperator", "0131_ledger_segregation_principal_changes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationrequest",
            options={"ordering": ["name"]},
        ),
    ]
