# Generated by Django 5.0.8 on 2024-12-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercialoperator", "0132_alter_organisationrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="last_event_application_fee_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="The last date a fee was charged for an Event Application",
            ),
        ),
    ]
