# Generated by Django 5.0.8 on 2024-12-10 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercialoperator",
            "0133_alter_organisation_last_event_application_fee_date",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUserAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("what", models.TextField()),
                ("email_user", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmailUserLogEntry",
            fields=[
                (
                    "communicationslogentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="commercialoperator.communicationslogentry",
                    ),
                ),
                ("emailuser", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
            bases=("commercialoperator.communicationslogentry",),
        ),
    ]
