# Generated by Django 5.2.5 on 2025-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercialoperator", "0134_emailuseraction_emailuserlogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenceperiod",
            name="licence_period",
            field=models.CharField(
                choices=[
                    ("2_months", "2 months"),
                    ("1_year", "1 Year"),
                    ("3_year", "3 Years"),
                    ("5_year", "5 Years"),
                    ("7_year", "7 Years"),
                    ("10_year", "10 Years"),
                    ("20_year", "20 Years"),
                ],
                default="1_year",
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposalotherdetails",
            name="preferred_licence_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2_months", "2 months"),
                    ("1_year", "1 Year"),
                    ("3_year", "3 Years"),
                    ("5_year", "5 Years"),
                    ("7_year", "7 Years"),
                    ("10_year", "10 Years"),
                    ("20_year", "20 Years"),
                ],
                max_length=40,
                null=True,
                verbose_name="Preferred licence period",
            ),
        ),
    ]
