# Generated by Django 5.2.12 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercialoperator", "0139_add_privacy_policy_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="key",
            field=models.CharField(
                choices=[
                    ("credit_facility_link", "Credit Facility Link"),
                    ("deed_poll", "Deed poll"),
                    ("deed_poll_filming", "Deed poll Filming"),
                    ("deed_poll_event", "Deed poll Event"),
                    (
                        "online_training_document",
                        "Online Training Document (Commercial Operations)",
                    ),
                    (
                        "event_online_training_document",
                        "Online Training Document (Event)",
                    ),
                    ("park_finder_link", "Park Finder Link"),
                    ("fees_and_charges", "Fees and charges link"),
                    ("event_fees_and_charges", "Event Fees and charges link"),
                    (
                        "commercial_filming_handbook",
                        "Commercial Filming Handbook link",
                    ),
                    ("park_stay_link", "Park Stay Link"),
                    (
                        "event_traffic_code_of_practice",
                        "Event traffic code of practice",
                    ),
                    ("trail_section_map", "Trail section map"),
                    ("dwer_application_form", "DWER Application Form"),
                    ("tourism_standards_link", "Tourism Standards Link"),
                    ("privacy_policy_url", "Privacy Policy URL"),
                ],
                max_length=255,
            ),
        ),
    ]
