# Generated by Django 5.2.15 on 2026-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0140_organisation_property_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cmd', models.CharField(blank=True, max_length=1000, null=True)),
                ('system_id', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('parameters_json', models.JSONField(blank=True, null=True)),
                ('processed_dt', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proposalaccreditation',
            name='accreditation_type',
            field=models.CharField(choices=[('no', 'None'), ('atap', 'QTA'), ('eco_certification', 'Eco Certification'), ('other', 'Other')], default='no', max_length=40, verbose_name='Accreditation'),
        ),
    ]
