# Generated by Django 5.2.15 on 2026-07-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0141_jobqueue_and_more'),
        ('commercialoperator', '0141_merge_20260629_1030'),
    ]

    operations = [
    ]
