# Generated by Django 5.2.16 on 2026-09-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0140_add_event_online_training_document'),
        ('commercialoperator', '0144_add_civil_aviation_safety_authority_link'),
    ]

    operations = [
    ]
