# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0118_park_visible_to_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='notification_only',
            field=models.BooleanField(default=False),
        ),
    ]
