# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0121_auto_20210806_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='charge_once_per_year',
            field=models.DateField(blank=True, null=True, verbose_name='Charge Application Fee once per year from given start date (Charge always if null)'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='max_num_months_ahead',
            field=models.SmallIntegerField(default=0, verbose_name='Maximum number of months ahead an Event can be booked (Any if equal to zero)'),
        ),
    ]
