# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-12 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0126_organisationcontactdeclineddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='num_child_participants',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of child participants'),
        ),
    ]
