# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0127_compliance_num_child_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='is_gst_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
